# config/app.yml for rails-settings-cached

defaults: &defaults
  sitename: "Foodblog"
  about: "About Text!"
  text_rows: 10
  max_portions: 30

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
